2024-05-10 13:20:42.300000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; se esperaba "identifier"
Syntax error in SQL statement "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; expected "identifier"; SQL statement:
CREATE TABLE book (

   titulo VARCHAR(50) PRIMARY KEY,

   autor VARCHAR(50),

   anopublicacion number(4),) [42001-224]
2024-05-10 13:20:53.329000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "drop table book\000d\000a[*]CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),)"
Syntax error in SQL statement "drop table book\000d\000a[*]CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),)"; SQL statement:
drop table book
CREATE TABLE book (

   titulo VARCHAR(50) PRIMARY KEY,

   autor VARCHAR(50),

   anopublicacion number(4),) [42000-224]
2024-05-10 13:21:04.030000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; se esperaba "identifier"
Syntax error in SQL statement "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; expected "identifier"; SQL statement:
CREATE TABLE book (

   titulo VARCHAR(50) PRIMARY KEY,

   autor VARCHAR(50),

   anopublicacion number(4),) [42001-224]
2024-05-10 13:21:09.941000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; se esperaba "identifier"
Syntax error in SQL statement "CREATE TABLE book (\000d\000a\000d\000a   titulo VARCHAR(50) PRIMARY KEY,\000d\000a\000d\000a   autor VARCHAR(50),\000d\000a\000d\000a   anopublicacion number(4),[*])"; expected "identifier"; SQL statement:
CREATE TABLE book (

   titulo VARCHAR(50) PRIMARY KEY,

   autor VARCHAR(50),

   anopublicacion number(4),) [42001-224]
2024-05-10 17:03:53.075084+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.example.DBConnection.DataSourceFactory.getDS(DataSourceFactory.kt:25)
	at org.example.MainKt.main(Main.kt:11)
	at org.example.MainKt.main(Main.kt)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 19 more
2024-05-10 17:05:58.987072+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "funcion lamdba" no encontrada
Column "funcion lamdba" not found [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at BookDao.getAll(BookDao.kt:72)
	at org.example.MainKt.main(Main.kt:19)
	at org.example.MainKt.main(Main.kt)
2024-05-10 17:07:21.060678+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "funcion lamdba" no encontrada
Column "funcion lamdba" not found [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at BookDao.getAll(BookDao.kt:72)
	at org.example.MainKt.main(Main.kt:19)
	at org.example.MainKt.main(Main.kt)
2024-05-10 17:08:27.428000+02:00 database: wrong user or password; user: "USER"
org.h2.message.DbException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-224]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.engine.Engine.openSession(Engine.java:154)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:288)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:811)
	at org.h2.server.web.WebApp.login(WebApp.java:1039)
	at org.h2.server.web.WebApp.process(WebApp.java:227)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:177)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:522)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2024-05-10 17:09:18.521810+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.example.DBConnection.DataSourceFactory.getDS(DataSourceFactory.kt:25)
	at org.example.MainKt.main(Main.kt:11)
	at org.example.MainKt.main(Main.kt)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 19 more
2024-05-10 17:09:27.637947+02:00 database: flush
org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.example.DBConnection.DataSourceFactory.getDS(DataSourceFactory.kt:25)
	at org.example.MainKt.main(Main.kt:11)
	at org.example.MainKt.main(Main.kt)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: E:/3 trimestre/programacion/untitled/default.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 19 more
2024-05-10 17:09:51.250026+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "funcion lamdba" no encontrada
Column "funcion lamdba" not found [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at BookDao.getAll(BookDao.kt:72)
	at org.example.MainKt.main(Main.kt:19)
	at org.example.MainKt.main(Main.kt)
2024-05-10 17:10:34.742337+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Columna "funcion lamdba" no encontrada
Column "funcion lamdba" not found [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:301)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at BookDao.selectById(BookDao.kt:46)
	at org.example.MainKt.main(Main.kt:17)
	at org.example.MainKt.main(Main.kt)
2024-05-10 17:25:50.033000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "[*]ater table add estado boolean"; se esperaba "ALTER, ANALYZE"
Syntax error in SQL statement "[*]ater table add estado boolean"; expected "ALTER, ANALYZE"; SQL statement:
ater table add estado boolean [42001-224]
2024-05-10 17:26:21.319000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "[*]ater table \000d\000aadd column estado boolean"; se esperaba "ALTER, ANALYZE"
Syntax error in SQL statement "[*]ater table \000d\000aadd column estado boolean"; expected "ALTER, ANALYZE"; SQL statement:
ater table 
add column estado boolean [42001-224]
2024-05-10 17:36:41.971000+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Error General : "Error General : ""org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]""\000aGeneral error: ""org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]"" [50000-224]"
General error: "Error General : ""org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]""\000aGeneral error: ""org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]"" [50000-224]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.engine.Database.throwLastBackgroundException(Database.java:1817)
	at org.h2.engine.SessionLocal.close(SessionLocal.java:890)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:391)
	at org.h2.server.web.WebApp.logout(WebApp.java:1066)
	at org.h2.server.web.WebApp.process(WebApp.java:233)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:177)
	at org.h2.server.web.WebThread.process(WebThread.java:154)
	at org.h2.server.web.WebThread.run(WebThread.java:103)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.message.DbException: Error General : "org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]"
General error: "org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.FileStore.storeBuffer(FileStore.java:1527)
	at org.h2.mvstore.FileStore.lambda$serializeAndStore$3(FileStore.java:1432)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]"
General error: "org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 12 more
Caused by: org.h2.mvstore.MVStoreException: Writing to sun.nio.ch.FileChannelImpl@3c5cf276 failed; length 4096 at 12288 [2.2.224/2]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:478)
	at org.h2.mvstore.SingleFileStore.writeFully(SingleFileStore.java:67)
	at org.h2.mvstore.SingleFileStore.writeFully(SingleFileStore.java:28)
	at org.h2.mvstore.RandomAccessStore.writeChunk(RandomAccessStore.java:366)
	at org.h2.mvstore.RandomAccessStore.writeChunk(RandomAccessStore.java:28)
	at org.h2.mvstore.FileStore.storeBuffer(FileStore.java:1524)
	... 6 more
Caused by: java.io.IOException: El dispositivo no estรก listo
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.FileChannelImpl.writeInternal(Unknown Source)
	at sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:474)
	... 11 more
